apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsql-client
  labels:
    app: cloudsql-client
spec:
  selector:
    matchLabels:
      app: cloudsql-client
  template:
    metadata:
      labels:
        app: cloudsql-client
    spec:
      containers:
        - name: cloudsql-client
          image: gcr.io/${PROJECT_ID}/${_REPO_PREFIX}/${REPO_NAME}
          imagePullPolicy: Always
          env:
            - name: CLOUDSQL_DB_HOST
              value: 127.0.0.1:3306
            # These secrets are required to start the pod.
            # [START cloudsql_connection]
            - name: INSTANCE_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-instance-connection
                  key: connection
            - name: CLOUD_SQL_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-instance-connection
                  key: name
            - name: CLOUDSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: CLOUDSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            # [END cloudsql_secrets]
